### PR TITLE
Fix old modmail "loaded in: NaN"

### LINKED ISSUE #138: Mod mail loaded in: NaN seconds
Using Microsoft Edge Dev (yes) and the chromium reddit-moderator-toolbox, on the modmail I get the following message : « mod mail loaded in: NaN seconds ».

https://github.com/toolbox-team/reddit-moderator-toolbox/blob/b3e7442e28f64c1d0f547a4601d1ba12622117b0/extension/data/modules/modmailpro.js#L692

### PR DESCRIPTION
**Pull request by k3n**
Fixes #138.

### CODE REVIEW

File: extension/data/modules/modmailpro.js [hunk 1]
```diff
@@ -249,6 +249,7 @@ function modmailpro () {
         $menuList.after($mmpMenu);
         self.endProfile('menu-gen');
 
+        let profileStart = performance.now();
```
Comment (k3n) [inline extension/data/modules/modmailpro.js]: There's 2 other places this is assigned a value, but they're both within click callbacks, so I'm not sure how this worked previously but this seems to fix it.

Comment (creesch) [reply extension/data/modules/modmailpro.js]: Cool, good enough for me. This is a legacy module anyway which we only keep around for those grumpy mods refusing to use new modmail ;)
